#!/usr/bin/env node
// .claude/agents/*.md(정본) → .codex/agents/*.toml(Codex)과 .agents/agents/*.md(Antigravity) 생성. --check는 차이만 검사한다.
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	realpathSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HEADER =
	"# generated by scripts/sync-agents.mjs from .claude/agents — 직접 수정하지 말 것";
const MD_HEADER = `<!-- ${HEADER.slice(2)} -->`;

export function parseAgent(md) {
	const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
	if (!m) throw new Error("frontmatter가 없다");
	const meta = {};
	for (const line of m[1].split(/\r?\n/)) {
		const kv = line.match(/^([\w-]+):\s*(.*)$/);
		if (kv)
			meta[kv[1]] = kv[2]
				.trim()
				.replace(/^"(.*)"$/, "$1")
				.replace(/^'(.*)'$/, "$1");
	}
	for (const k of ["name", "description"])
		if (!meta[k]) throw new Error(`frontmatter에 ${k}가 없다`);
	return { meta, body: m[2].trim() };
}

// tools가 없거나 Write·Edit가 있으면 파일을 쓰는 에이전트다
const writes = (meta) => {
	const tools = meta.tools ? meta.tools.split(",").map((t) => t.trim()) : null;
	return !tools || tools.includes("Write") || tools.includes("Edit");
};

export function toToml({ meta, body }) {
	if (body.includes("'''"))
		throw new Error(`${meta.name}: 본문에 ''' 를 쓸 수 없다`);
	const sandbox = writes(meta) ? "workspace-write" : "read-only";
	return [
		HEADER,
		`name = ${JSON.stringify(meta.name)}`,
		`description = ${JSON.stringify(meta.description)}`,
		`sandbox_mode = "${sandbox}"`,
		"developer_instructions = '''",
		body,
		"'''",
		"",
	].join("\n");
}

// Antigravity 서브에이전트(.agents/agents/<name>.md). 메인 에이전트로는 고르지 않는다(mainAgent: false).
// 쓰기 도구가 없는 에이전트(Codex read-only와 같은 기준)는 공식 문서 예시의 세 도구만 준다. 문서에 도구 전체 목록이 없고
// 틀린 이름은 서브에이전트를 멈추게 할 수 있어서 이름을 더하지 않는다. 쓰기 에이전트는 tools를 빼서 부모 도구를 그대로 쓴다.
const AG_READ_TOOLS = ["view_file", "grep_search", "run_command"];
export function toAntigravity({ meta, body }) {
	return [
		"---",
		`name: ${meta.name}`,
		`description: ${JSON.stringify(meta.description)}`,
		"mainAgent: false",
		...(writes(meta)
			? []
			: ["tools:", ...AG_READ_TOOLS.map((t) => `  - ${t}`)]),
		"---",
		MD_HEADER,
		"",
		body,
		"",
	].join("\n");
}

// 생성물: Codex는 TOML, Antigravity는 md. Grok Build는 .claude/agents를 그대로 읽는다.
const TARGETS = [
	{
		dir: ".codex/agents",
		ext: ".toml",
		render: toToml,
		ours: (s) => s.startsWith(HEADER),
	},
	{
		dir: ".agents/agents",
		ext: ".md",
		render: toAntigravity,
		ours: (s) => s.includes(MD_HEADER),
	},
];

export function sync(root, { check = false } = {}) {
	const src = join(root, ".claude/agents");
	const agents = [];
	for (const f of readdirSync(src)
		.filter((f) => f.endsWith(".md"))
		.sort()) {
		const agent = parseAgent(readFileSync(join(src, f), "utf8"));
		const name = agent.meta.name;
		if (!/^[\w-]+$/.test(name ?? ""))
			throw new Error(`${f}: name은 영문·숫자·_·-만 쓴다 (현재 ${name})`);
		// 대소문자만 다른 이름은 macOS 기본 디스크에서 같은 파일이 된다.
		if (agents.some((a) => a.meta.name.toLowerCase() === name.toLowerCase()))
			throw new Error(`${f}: name ${name} 중복`);
		agents.push(agent);
	}
	const diffs = [];
	for (const { dir, ext, render, ours } of TARGETS) {
		const out = join(root, dir);
		const expected = new Map(agents.map((a) => [a.meta.name + ext, render(a)]));
		for (const [f, content] of expected) {
			const p = join(out, f);
			const cur = existsSync(p) ? readFileSync(p, "utf8") : null;
			if (cur === content) continue;
			diffs.push(`${cur === null ? "누락" : "불일치"}: ${dir}/${f}`);
			if (!check) {
				mkdirSync(out, { recursive: true });
				writeFileSync(p, content);
			}
		}
		const existing = existsSync(out)
			? readdirSync(out).filter((f) => f.endsWith(ext))
			: [];
		for (const f of existing) {
			if (expected.has(f) || !ours(readFileSync(join(out, f), "utf8")))
				continue;
			diffs.push(`고아 생성물: ${dir}/${f}`);
			if (!check) unlinkSync(join(out, f));
		}
	}
	return diffs;
}

// 실재 경로로 비교한다. 심볼릭 링크 경로(macOS /tmp 등)로 실행하면 argv와 import.meta.url이 달라진다.
const isMain = () => {
	try {
		return realpathSync(process.argv[1]) === fileURLToPath(import.meta.url);
	} catch {
		return false;
	}
};
if (isMain()) {
	const check = process.argv.includes("--check");
	try {
		const diffs = sync(process.cwd(), { check });
		if (check && diffs.length) {
			console.log(
				[
					"에이전트 정의가 생성물과 다르다 (pnpm agents:sync):",
					...diffs.map((d) => `  ${d}`),
				].join("\n"),
			);
			process.exitCode = 1;
		} else {
			console.log(
				diffs.length
					? diffs.map((d) => `갱신 — ${d}`).join("\n")
					: "에이전트 정의 일치",
			);
		}
	} catch (e) {
		console.error(e.message);
		process.exitCode = 2;
	}
}
