// 표시 없이 묶음 원본과 같은 글로 둔 곳(CASES): [파일, 묶음 이름, 인자].
// 목록 한 줄·표 한 행처럼 묶음 표시를 달면 목록·표가 끊기는 곳은 표시 없이 묶음 원본을 펼친 글과 같게 두고,
// scripts/doc-values.test.mjs가 같은지 본다. 표시를 단 곳은 --check가 보므로 테스트가 건너뛴다(인자는 표시에 그대로 옮길 값이다).
// scripts/doc-values.mjs는 이 목록으로 docs/common-values.md 목록 표의 "쓰는 곳"에 CASES 수를 더한다.
const PRESETS = {
  ullim: { remix: { folder: "storyvoice", title: "이야기 소리", changes: "주제는 어린이 동화 낭독, 제목 서체는 더 둥글게", topic: "주제는 어린이 동화 낭독" }, concept: "혼자 영상이나 팟캐스트를 만드는 사람이 대본을 붙여 넣으면 내레이션 음성을 만들어 주고, 문장마다 억양과 쉼을 고칠 수 있게 해 주는 서비스" },
  jecheol: { remix: { folder: "sea-box", title: "제철바다", changes: "상품은 제철 수산물, 대표 색은 바다 파랑", topic: "주제는 제철 수산물 정기배송" }, concept: "1~2인 가구 직장인이 제철 채소와 과일을 2주마다 상자로 받아 보고, 건너뛰기와 해지도 쉽게 할 수 있는 정기배송 서비스" },
  pacecrew: { remix: { folder: "ridecrew", title: "RIDECREW", changes: "주제는 동네 자전거 라이딩 크루, 대표 색은 형광 주황", topic: "주제는 동네 자전거 라이딩 크루" }, concept: "혼자 뛰는 러너가 우리 동네에서 내 페이스에 맞는 러닝 크루를 찾아 가입하고, 크루끼리 여는 주말 레이스에 신청하는 서비스" },
  afterglow: { remix: { folder: "warmcore", title: "온기", changes: "제품은 가정용 히트펌프, 대표 색은 청록", topic: "주제는 가정용 히트펌프 판매" }, concept: "지붕에 태양광을 단 집에 가정용 배터리를 팔고, 설치 상담 신청과 설치한 뒤 우리 집 에너지 확인까지 해 주는 서비스" },
  goru: { remix: { folder: "club-dues", title: "우리 동아리 회비", changes: "주제는 동아리 회비 정산, 대표 색은 짙은 파랑", topic: "주제는 동아리 회비 정산" }, concept: "같이 사는 2~4명이 함께 쓴 생활비를 적고, 월말에 송금 횟수가 가장 적게 정산해 주는 서비스" },
  fitslot: { remix: { folder: "yogaslot", title: "요가슬롯", changes: "주제는 동네 요가 스튜디오, 대표 색은 진한 남색", topic: "주제는 동네 요가 스튜디오 예약" }, concept: "동네 필라테스 스튜디오 회원이 이번 주 시간표에서 빈자리를 찾아 수업을 예약하고 취소하고, 남은 수강권을 확인하는 서비스" },
  uptrail: { order: true, remix: { folder: "jobtrail", title: "Jobtrail", changes: "주제는 데이터 파이프라인 작업 모니터링, 대표 색은 초록", topic: "주제는 데이터 파이프라인 작업 모니터링" }, concept: "5~20명 규모 개발팀이 자기 서비스들의 상태와 최근 배포를 한 화면에서 보고, 장애가 나면 어느 배포 뒤에 났는지 찾는 모니터링 서비스" },
  studyday: { remix: { folder: "cert-day", title: "자격증 하루", changes: "주제는 자격증 시험 준비, 대표 색은 하늘색", topic: "주제는 자격증 시험 준비" }, concept: "혼자 시험을 준비하는 사람이 시험 날짜와 과목별 분량을 넣으면 하루 할 일로 나눠 주고, 끝낸 일과 공부 시간을 기록하는 서비스" },
  olgot: { order: true, remix: { folder: "olgot-english", title: "올곧 영어", changes: "주제는 고등부 영어 입시학원, 대표 색은 짙은 초록", topic: "주제는 고등부 영어 입시학원" }, concept: "고1~고3 학생과 학부모가 학년·과목별 시간표에서 수학·과학 반을 찾아 수강 신청과 대기 신청을 하고 입시 설명회를 예약하며, 재원생은 신청 내역과 복습 영상, 성적을 보는 입시학원 사이트" },
};
export const LIVING = { folder: "living", concept: "같이 사는 사람들이 함께 쓴 생활비를 적고, 월말에 누가 누구에게 얼마를 보내면 되는지 알려 주는 서비스" };
// 두 템플릿 README(prokit-next-neon, prokit-next-supabase)의 같은 글. [묶음 이름(tpl-readme- 뒤), neon 인자, supabase 인자]
const TPL = ["prokit-next-neon", "prokit-next-supabase"];
export const TPL_README = [
  ["license", {}, {}],
  ["install-rows", { db: "neon" }, { db: "supabase" }],
  ["prereq-node", {}, {}],
  ["prereq-tools", { cli: "Neon CLI" }, { cli: "Supabase CLI", tail: ". Supabase CLI는 Homebrew가 필요하다" }],
  ["windows-intro", {}, { tail: " Windows에서 바로 Supabase와 Podman을 함께 쓰면 실패한다는 보고도 있다." }],
  ["windows-steps", {}, {}],
  ["windows-browser", { n: "4" }, { n: "5" }],
  ["start-note", {}, {}],
  ["screen-only", {}, {}],
  ["after-install-format", {}, { dir: "`packages/db/supabase/`(`config.toml`, `.gitignore`), " }],
  ["after-install-steps", {}, {}],
  ["clone", {}, { tail: " 로컬 DB는 `packages/db`에서 `supabase start ...` 뒤 `db:migrate`로 만든다." }],
  ["update-existing", {}, {}],
  ["vercel-intro", {}, {}],
  ["vercel-env-rule", {}, {}],
  ["vercel-env-files", {}, {}],
  ["vercel-deploy", { url: "pooled 주소(`-pooler`)" }, { url: "transaction pooler 주소({{v:port.supabasePooler}})" }],
  ["vercel-notes", {}, {}],
  ["options", { cli: "Neon" }, { cli: "Supabase" }],
  ["commands", {}, {}],
  ["commands-plugin", {}, {}],
  ["dev", { me: TPL[0], other: TPL[1], josa: "와" }, { me: TPL[1], other: TPL[0], josa: "과" }],
];
export const CASES = [
  ["tutorials/samples/README.md", "screen-prompt", LIVING],
  ["tutorials/reference/deploy.md", "screen-prompt", { ...LIVING, end: "[GitHub Pages]에 배포해줘" }],
  ["tutorials/reference/process-and-time.md", "screen-prompt", { folder: "my-bakery", concept: "동네 빵집에서 빵을 미리 주문하고 찾아가는 서비스", ref: " [참고할 서비스 주소]의 공개 페이지를 먼저 둘러보고 화면 구성과 디자인 값을 정리한 뒤, 그걸 바탕으로 기획하고 디자인해줘. 로고와 이름, 문구, 사진은 가져오지 말고, 원래 서비스와 관계없는 연습용이라고 화면에 밝혀줘.", design: "디자인은 정리한 디자인 값을 따르되 색과 서체는 비슷한 계열의 다른 것으로 바꾸고, " }],
  ["tutorials/reference/process-and-time.md", "process-flow-diagram", {}],
  ["tutorials/reference/process-and-time.md", "process-pie", { name: "claudle", title: "Claudle 만들기, 무엇에 시간이 갔나(분)" }],
  ["tutorials/reference/process-and-time.md", "process-pie", { name: "olgot", title: "올곧 만들기, 무엇에 시간이 갔나(분)" }],
  ["tutorials/reference/process-and-time.md", "process-gantt-claudle", {}],
  ["tutorials/reference/process-and-time.md", "revise-flow-gantt", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-prep-note", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-prep-note", {}],
  ["tutorials/start/README.md", "yolo-option", {}],
  ["tutorials/samples/README.md", "yolo-option", { tail: "" }],
  ["tutorials/start/README.md", "yolo-warning", {}],
  ["tutorials/samples/README.md", "yolo-warning", {}],
  ["tutorials/01-nextflix/README.md", "yolo-warning-short", {}],
  ["tutorials/02-claudle/README.md", "yolo-warning-short", {}],
  ["tutorials/start/README.md", "start-check-prompt", {}],
  ["tutorials/start/README.md", "install-claude", {}],
  ["tutorials/start/README.md", "install-codex", {}],
  ["tutorials/reference/costs-and-keys.md", "install-codex", {}],
  ["tutorials/samples/README.md", "cost-note", {}],
  ["tutorials/01-nextflix/README.md", "cost-note", {}],
  ["tutorials/02-claudle/README.md", "cost-note", {}],
  ["tutorials/samples/README.md", "revise-time-detail", {}],
  ["tutorials/01-nextflix/README.md", "revise-time-detail", {}],
  ["tutorials/02-claudle/README.md", "revise-time-detail", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-stage-note", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-stage-note", {}],
  ["tutorials/samples/afterglow.md", "revise-time-detail", {}],
  ["tutorials/samples/afterglow.md", "preset-stage-intro", {}],
  ["tutorials/samples/fitslot.md", "revise-time-detail", {}],
  ["tutorials/samples/fitslot.md", "preset-stage-intro", {}],
  ["tutorials/samples/goru.md", "revise-time-detail", {}],
  ["tutorials/samples/goru.md", "preset-stage-intro", {}],
  ["tutorials/samples/jecheol.md", "revise-time-detail", {}],
  ["tutorials/samples/jecheol.md", "preset-stage-intro", {}],
  ["tutorials/samples/olgot.md", "revise-time-detail", {}],
  ["tutorials/samples/olgot.md", "preset-stage-intro", {}],
  ["tutorials/samples/pacecrew.md", "revise-time-detail", {}],
  ["tutorials/samples/pacecrew.md", "preset-stage-intro", {}],
  ["tutorials/samples/studyday.md", "revise-time-detail", {}],
  ["tutorials/samples/studyday.md", "preset-stage-intro", {}],
  ["tutorials/samples/ullim.md", "revise-time-detail", {}],
  ["tutorials/samples/ullim.md", "preset-stage-intro", {}],
  ["tutorials/samples/uptrail.md", "revise-time-detail", {}],
  ["tutorials/samples/uptrail.md", "preset-stage-intro", {}],
  ["tutorials/start/README.md", "open-agent", {}],
  ["tutorials/start/README.md", "open-agent", { cd: "cd ~/projects/pro-kit" }],
  ["tutorials/samples/README.md", "open-agent", {}],
  ["tutorials/samples/README.md", "open-agent", { cd: "cd ~/projects" }],
  ["tutorials/samples/README.md", "open-agent", { cd: "cd ~/projects/living" }],
  ["tutorials/samples/01-project.md", "open-agent", { cd: "cd ~/projects/living" }],
  ["tutorials/samples/real-service.md", "open-agent", { cd: "cd ~/projects/living-app" }],
  ["tutorials/01-nextflix/README.md", "open-agent", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "open-agent", { cd: "cd ~/projects/nextflix" }],
  ["tutorials/02-claudle/README.md", "open-agent", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "open-agent", { cd: "cd ~/projects/claudle" }],
  ["tutorials/samples/README.md", "first-trouble", { folder: "living" }],
  ["tutorials/samples/README.md", "samples-trouble", { folder: "living" }],
  ["tutorials/01-nextflix/README.md", "first-trouble", { folder: "nextflix" }],
  ["tutorials/02-claudle/README.md", "first-trouble", { folder: "claudle" }],
  ["tutorials/01-nextflix/README.md", "course-trouble", { folder: "nextflix", name: "nextflix", iyo: "예요" }],
  ["tutorials/02-claudle/README.md", "course-trouble", { folder: "claudle", name: "claudle", iyo: "이에요" }],
  ["tutorials/01-nextflix/README.md", "trouble-pack", { name: "nextflix" }],
  ["tutorials/01-nextflix/05-auth-profiles.md", "trouble-pack", { name: "nextflix" }],
  ["tutorials/02-claudle/README.md", "trouble-pack", { name: "claudle" }],
  ["tutorials/02-claudle/05-auth-chats.md", "trouble-pack", { name: "claudle" }],
  ["tutorials/01-nextflix/02-plan.md", "trouble-pack", { name: "nextflix", lead: "`~/projects` 안에 `pro-kit`과 `nextflix`가 나란히 있는지 보세요. 있으면 " }],
  ["tutorials/01-nextflix/03-design.md", "trouble-pack", { name: "nextflix" }],
  ["tutorials/01-nextflix/06-catalog-db.md", "trouble-pack", { name: "nextflix" }],
  ["tutorials/02-claudle/02-plan.md", "trouble-pack", { name: "claudle", lead: "`~/projects` 안에 `pro-kit`과 `claudle`이 나란히 있는지 보세요. 있으면 " }],
  ["tutorials/02-claudle/03-design.md", "trouble-pack", { name: "claudle" }],
  ["tutorials/reference/deploy.md", "trouble-password", {}],
  ["tutorials/samples/01-project.md", "trouble-password", {}],
  ["tutorials/01-nextflix/01-create-project.md", "open-with-hooks", { folder: "nextflix" }],
  ["tutorials/02-claudle/01-create-project.md", "open-with-hooks", { folder: "claudle" }],
  ["tutorials/01-nextflix/README.md", "continue-line", { folder: "nextflix" }],
  ["tutorials/02-claudle/README.md", "continue-line", { folder: "claudle" }],
  ["tutorials/samples/README.md", "continue-line", { folder: "living" }],
  ["handbook/start/quickstart-service.md", "open-in-kit", {}],
  ["handbook/start/after-create.md", "open-in-project", {}],
  ["handbook/design/ui-flow.md", "ui-flow-diagram", {}],
  ["handbook/design/design-md.md", "design-md-effect-chart", {}],
  ["handbook/templates/what-it-adds.md", "what-it-adds-diagram", {}],
  ["handbook/reference/project-structure.md", "project-structure-tree", {}],
  ["tutorials/01-nextflix/README.md", "open-already-line", {}],
  ["tutorials/01-nextflix/README.md", "yolo-option", { tail: "" }],
  ["tutorials/02-claudle/README.md", "open-already-line", {}],
  ["tutorials/02-claudle/README.md", "yolo-option", { tail: "" }],
  ["tutorials/01-nextflix/01-create-project.md", "trouble-other", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "trouble-other", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "trouble-other", {}],
  ["tutorials/01-nextflix/07-search.md", "trouble-other", {}],
  ["tutorials/01-nextflix/08-my-list.md", "trouble-other", {}],
  ["tutorials/01-nextflix/09-rating.md", "trouble-other", {}],
  ["tutorials/01-nextflix/10-watch.md", "trouble-other", {}],
  ["tutorials/01-nextflix/11-check.md", "trouble-other", {}],
  ["tutorials/01-nextflix/12-deploy.md", "trouble-other", {}],
  ["tutorials/01-nextflix/README.md", "trouble-other", {}],
  ["tutorials/02-claudle/01-create-project.md", "trouble-other", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "trouble-other", {}],
  ["tutorials/02-claudle/06-chat-manage.md", "trouble-other", {}],
  ["tutorials/02-claudle/07-ai-reply.md", "trouble-other", {}],
  ["tutorials/02-claudle/08-search.md", "trouble-other", {}],
  ["tutorials/02-claudle/09-projects.md", "trouble-other", {}],
  ["tutorials/02-claudle/10-artifacts.md", "trouble-other", {}],
  ["tutorials/02-claudle/11-check.md", "trouble-other", {}],
  ["tutorials/02-claudle/12-deploy.md", "trouble-other", {}],
  ["tutorials/02-claudle/README.md", "trouble-other", {}],
  ["tutorials/samples/README.md", "trouble-other", {}],
  ["tutorials/02-claudle/03-design.md", "qa-row-color", {}],
  ["tutorials/01-nextflix/04-screens.md", "qa-row-polish", {}],
  ["tutorials/01-nextflix/11-check.md", "qa-row-polish", {}],
  ["tutorials/01-nextflix/README.md", "qa-row-polish", {}],
  ["tutorials/02-claudle/04-screens.md", "qa-row-polish", {}],
  ["tutorials/02-claudle/11-check.md", "qa-row-polish", {}],
  ["tutorials/02-claudle/README.md", "qa-row-polish", {}],
  ["tutorials/samples/06-review.md", "qa-row-polish", {}],
  ["tutorials/samples/README.md", "qa-row-polish", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "trouble-db", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "trouble-db", {}],
  ["tutorials/01-nextflix/07-search.md", "trouble-db", {}],
  ["tutorials/01-nextflix/10-watch.md", "trouble-db", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "trouble-db", {}],
  ["tutorials/01-nextflix/07-search.md", "trouble-prev-chapter", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/08-my-list.md", "trouble-prev-chapter", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/09-rating.md", "trouble-prev-chapter", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/10-watch.md", "trouble-prev-chapter", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/06-chat-manage.md", "trouble-prev-chapter", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/07-ai-reply.md", "trouble-prev-chapter", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/08-search.md", "trouble-prev-chapter", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/09-projects.md", "trouble-prev-chapter", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/10-artifacts.md", "trouble-prev-chapter", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/07-search.md", "feature-round-intro", {}],
  ["tutorials/01-nextflix/08-my-list.md", "feature-round-intro", {}],
  ["tutorials/01-nextflix/09-rating.md", "feature-round-intro", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "feature-round-spec", {}],
  ["tutorials/01-nextflix/07-search.md", "feature-round-spec", {}],
  ["tutorials/01-nextflix/08-my-list.md", "feature-round-spec", {}],
  ["tutorials/01-nextflix/09-rating.md", "feature-round-spec", {}],
  ["tutorials/01-nextflix/10-watch.md", "feature-round-spec", {}],
  ["tutorials/02-claudle/06-chat-manage.md", "feature-round-spec", {}],
  ["tutorials/02-claudle/07-ai-reply.md", "feature-round-spec", {}],
  ["tutorials/02-claudle/08-search.md", "feature-round-spec", {}],
  ["tutorials/02-claudle/09-projects.md", "feature-round-spec", {}],
  ["tutorials/02-claudle/10-artifacts.md", "feature-round-spec", {}],
  ["tutorials/01-nextflix/README.md", "exit-line", {}],
  ["tutorials/02-claudle/README.md", "exit-line", {}],
  ["tutorials/samples/README.md", "exit-line", {}],
  ["tutorials/samples/README.md", "open-already-line", {}],
  ["tutorials/01-nextflix/README.md", "open-new-folder", {}],
  ["tutorials/02-claudle/README.md", "open-new-folder", {}],
  ["tutorials/samples/README.md", "open-new-folder", { extra: "결과물의 품질이 여기서 나와요. " }],
  ["tutorials/01-nextflix/README.md", "codex-hooks-line", {}],
  ["tutorials/02-claudle/README.md", "codex-hooks-line", {}],
  ["tutorials/01-nextflix/01-create-project.md", "codex-hooks-line", {}],
  ["tutorials/02-claudle/01-create-project.md", "codex-hooks-line", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "feature-round-outro", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/07-search.md", "feature-round-outro", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/08-my-list.md", "feature-round-outro", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/09-rating.md", "feature-round-outro", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/10-watch.md", "feature-round-outro", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/06-chat-manage.md", "feature-round-outro", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/07-ai-reply.md", "feature-round-outro", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/08-search.md", "feature-round-outro", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/09-projects.md", "feature-round-outro", { auth: "05-auth-chats.md" }],
  ["tutorials/02-claudle/10-artifacts.md", "feature-round-outro", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/06-catalog-db.md", "qa-row-spec", {}],
  ["tutorials/01-nextflix/07-search.md", "qa-row-spec", {}],
  ["tutorials/01-nextflix/08-my-list.md", "qa-row-spec", {}],
  ["tutorials/01-nextflix/09-rating.md", "qa-row-spec", {}],
  ["tutorials/01-nextflix/10-watch.md", "qa-row-spec", {}],
  ["tutorials/02-claudle/06-chat-manage.md", "qa-row-spec", {}],
  ["tutorials/02-claudle/07-ai-reply.md", "qa-row-spec", {}],
  ["tutorials/02-claudle/08-search.md", "qa-row-spec", {}],
  ["tutorials/02-claudle/09-projects.md", "qa-row-spec", {}],
  ["tutorials/01-nextflix/04-screens.md", "trouble-stop", { name: "nextflix" }],
  ["tutorials/01-nextflix/05-auth-profiles.md", "trouble-stop", { name: "nextflix" }],
  ["tutorials/02-claudle/04-screens.md", "trouble-stop", { name: "claudle" }],
  ["tutorials/02-claudle/05-auth-chats.md", "trouble-stop", { name: "claudle" }],
  ["tutorials/01-nextflix/06-catalog-db.md", "trouble-prev-short", { auth: "05-auth-profiles.md" }],
  ["tutorials/01-nextflix/11-check.md", "trouble-prev-short", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/11-check.md", "trouble-prev-short", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/04-screens.md", "trouble-dev-server", {}],
  ["tutorials/02-claudle/04-screens.md", "trouble-dev-server", {}],
  ["tutorials/01-nextflix/README.md", "prompt-varies-line", {}],
  ["tutorials/02-claudle/README.md", "prompt-varies-line", {}],
  ["tutorials/samples/01-project.md", "agent-order-line", {}],
  ["tutorials/samples/01-project.md", "trouble-docker-skip", {}],
  ["tutorials/samples/05-build.md", "trouble-dev-server", {}],
  ["tutorials/samples/05-build.md", "qa-row-wireframe", {}],
  ["tutorials/samples/README.md", "workfolder-row", {}],
  ["tutorials/samples/README.md", "qa-row-confirm", {}],
  ["tutorials/samples/README.md", "prompt-varies-line", {}],
  ["tutorials/start/README.md", "trouble-other", {}],
  ["tutorials/samples/afterglow.md", "sample-stage-head", {}],
  ["tutorials/samples/afterglow.md", "sample-stage-first", {}],
  ["tutorials/samples/afterglow.md", "sample-stage-tail", {}],
  ["tutorials/samples/fitslot.md", "sample-stage-head", {}],
  ["tutorials/samples/fitslot.md", "sample-stage-first", {}],
  ["tutorials/samples/fitslot.md", "sample-stage-tail", {}],
  ["tutorials/samples/goru.md", "sample-stage-head", {}],
  ["tutorials/samples/goru.md", "sample-stage-first", {}],
  ["tutorials/samples/goru.md", "sample-stage-tail", {}],
  ["tutorials/samples/jecheol.md", "sample-stage-head", {}],
  ["tutorials/samples/jecheol.md", "sample-stage-first", {}],
  ["tutorials/samples/jecheol.md", "sample-stage-tail", {}],
  ["tutorials/samples/olgot.md", "sample-stage-head", {}],
  ["tutorials/samples/olgot.md", "sample-stage-first", {}],
  ["tutorials/samples/olgot.md", "sample-stage-tail", {}],
  ["tutorials/samples/pacecrew.md", "sample-stage-head", {}],
  ["tutorials/samples/pacecrew.md", "sample-stage-first", {}],
  ["tutorials/samples/pacecrew.md", "sample-stage-tail", {}],
  ["tutorials/samples/studyday.md", "sample-stage-head", {}],
  ["tutorials/samples/studyday.md", "sample-stage-first", {}],
  ["tutorials/samples/studyday.md", "sample-stage-tail", {}],
  ["tutorials/samples/ullim.md", "sample-stage-head", {}],
  ["tutorials/samples/ullim.md", "sample-stage-first", {}],
  ["tutorials/samples/ullim.md", "sample-stage-tail", {}],
  ["tutorials/samples/uptrail.md", "sample-stage-head", {}],
  ["tutorials/samples/uptrail.md", "sample-stage-first", {}],
  ["tutorials/samples/uptrail.md", "sample-stage-tail", {}],
  ["tutorials/reference/costs-and-keys.md", "env-vscode-steps", {}],
  ["tutorials/reference/deploy.md", "env-vscode-steps", {}],
  ["tutorials/reference/costs-and-keys.md", "env-vscode-tip", { what: "키를" }],
  ["tutorials/reference/deploy.md", "env-vscode-tip", { what: "토큰을" }],
  ["tutorials/samples/afterglow.md", "preset-time-line", { name: "afterglow" }],
  ["tutorials/samples/afterglow.md", "preset-actual-line", { name: "afterglow" }],
  ["tutorials/samples/fitslot.md", "preset-time-line", { name: "fitslot" }],
  ["tutorials/samples/fitslot.md", "preset-actual-line", { name: "fitslot" }],
  ["tutorials/samples/goru.md", "preset-time-line", { name: "goru" }],
  ["tutorials/samples/goru.md", "preset-actual-line", { name: "goru" }],
  ["tutorials/samples/jecheol.md", "preset-time-line", { name: "jecheol" }],
  ["tutorials/samples/jecheol.md", "preset-actual-line", { name: "jecheol" }],
  ["tutorials/samples/pacecrew.md", "preset-time-line", { name: "pacecrew" }],
  ["tutorials/samples/pacecrew.md", "preset-actual-line", { name: "pacecrew" }],
  ["tutorials/samples/studyday.md", "preset-time-line", { name: "studyday" }],
  ["tutorials/samples/studyday.md", "preset-actual-line", { name: "studyday" }],
  ["tutorials/samples/ullim.md", "preset-time-line", { name: "ullim" }],
  ["tutorials/samples/ullim.md", "preset-actual-line", { name: "ullim" }],
  ["tutorials/samples/uptrail.md", "preset-time-line", { name: "uptrail" }],
  ["tutorials/samples/uptrail.md", "preset-actual-line", { name: "uptrail" }],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-intro", { name: "nextflix" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-intro", { name: "claudle" }],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-prompt", { name: "nextflix" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-prompt", { name: "claudle" }],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-trouble", { name: "nextflix" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-trouble", { name: "claudle" }],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-reopen", {}],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-reopen", {}],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-hooks", {}],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-hooks", {}],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-qa", {}],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-qa", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-intro", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-intro", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-reads", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-reads", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-confirm", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-confirm", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-qa", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-qa", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-mockup-tip", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-mockup-tip", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-prompt", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-prompt", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-pick", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-pick", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-trouble-pick", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-trouble-pick", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-restyle-tip", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-restyle-tip", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-qa", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-qa", {}],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-confirmed", {}],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-confirmed", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-feature-note", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-feature-note", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-resume", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-resume", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-qa", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-qa", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-intro", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-intro", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-fix", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-fix", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-review", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-review", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-try", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-try", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-feedback", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-feedback", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-note", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-note", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-tools", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-tools", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-tools", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-tools", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-github", { name: "nextflix" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-github", { name: "claudle" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-neon", { name: "nextflix" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-neon", { name: "claudle" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-neon", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-neon", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-vercel", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-vercel", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-finish", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-finish", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-develop", { name: "nextflix" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-develop", { name: "claudle" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-develop", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-develop", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-qa-intro", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-qa-intro", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-pack", { name: "nextflix" }],
  ["tutorials/01-nextflix/README.md", "preset-pack-get", { name: "nextflix" }],
  ["tutorials/01-nextflix/README.md", "preset-pack-source", { name: "nextflix" }],
  ["tutorials/02-claudle/README.md", "clone-readme-pack", { name: "claudle" }],
  ["tutorials/02-claudle/README.md", "preset-pack-get", { name: "claudle" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-one-prompt", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-one-prompt", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-workfolder", { name: "nextflix" }],
  ["tutorials/02-claudle/README.md", "clone-readme-workfolder", { name: "claudle" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-db-note", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-db-note", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-chapters-intro", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-chapters-intro", {}],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-easy-note", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-easy-note", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-rename-tip", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-rename-tip", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-success-sitemap", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-success-sitemap", {}],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-trouble-answer", {}],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-trouble-answer", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-fetch-step", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-fetch-step", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-check-step", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-check-step", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-trouble-fetch", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-trouble-fetch", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-trouble-leftover", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-trouble-leftover", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-success-pick", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-success-pick", {}],
  ["tutorials/01-nextflix/03-design.md", "clone-design-next", {}],
  ["tutorials/02-claudle/03-design.md", "clone-design-next", {}],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-preset-site", { name: "nextflix" }],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-preset-site", { name: "claudle" }],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-steps-copy", {}],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-steps-copy", {}],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-steps-check", {}],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-steps-check", {}],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-review", {}],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-review", {}],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-trouble-images", { name: "nextflix" }],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-trouble-images", { name: "claudle" }],
  ["tutorials/01-nextflix/04-screens.md", "qa-row-review", {}],
  ["tutorials/02-claudle/04-screens.md", "qa-row-review", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-open", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-open", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-steps-review", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-steps-review", {}],
  ["tutorials/01-nextflix/05-auth-profiles.md", "clone-auth-trouble-prev", {}],
  ["tutorials/02-claudle/05-auth-chats.md", "clone-auth-trouble-prev", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-start", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-start", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-row-code", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-row-code", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-rows-screen", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-rows-screen", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-trouble-verify", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-trouble-verify", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-trouble-score", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-trouble-score", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-trouble-slow", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-trouble-slow", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-feedback-round", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-feedback-round", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-trouble-stale", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-trouble-stale", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-trouble-mobile", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-trouble-mobile", {}],
  ["tutorials/01-nextflix/11-check.md", "clone-check-last-tip", {}],
  ["tutorials/02-claudle/11-check.md", "clone-check-last-tip", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-who-rows", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-who-rows", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-origin", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-origin", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-vercel", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-vercel", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-vercel-steps", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-vercel-steps", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-vercel-check", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-vercel-check", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-prod-steps", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-prod-steps", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-prod-account", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-prod-account", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-prod", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-prod", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-trouble-rollback", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-trouble-rollback", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-qa-rows", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-qa-rows", {}],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-qa-finish", {}],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-qa-finish", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-qa-intro", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/README.md", "clone-readme-qa-intro", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-qa-rows", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-qa-rows", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-qa-tail", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-qa-tail", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-continue", { name: "nextflix", auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/README.md", "clone-readme-continue", { name: "claudle", auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-chapter-rows-start", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-chapter-rows-start", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-chapter-rows-end", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-chapter-rows-end", {}],
  ["tutorials/01-nextflix/README.md", "clone-readme-cost-basis", {}],
  ["tutorials/02-claudle/README.md", "clone-readme-cost-basis", {}],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-where", { name: "nextflix", neun: "는" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-where", { name: "claudle", neun: "은" }],
  ["tutorials/01-nextflix/01-create-project.md", "clone-create-mockup-prep", { pic: "작품 그림", home: "홈 화면" }],
  ["tutorials/02-claudle/01-create-project.md", "clone-create-mockup-prep", { pic: "그림", home: "홈 화면(소개 쪽)" }],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-start", { name: "nextflix", neun: "는" }],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-start", { name: "claudle", neun: "은" }],
  ["tutorials/01-nextflix/02-plan.md", "clone-plan-trouble-early", { name: "nextflix", ga: "가" }],
  ["tutorials/02-claudle/02-plan.md", "clone-plan-trouble-early", { name: "claudle", ga: "이" }],
  ["tutorials/01-nextflix/04-screens.md", "clone-screens-trouble-rename", { name: "nextflix", ga: "가" }],
  ["tutorials/02-claudle/04-screens.md", "clone-screens-trouble-rename", { name: "claudle", ga: "이" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-intro", { name: "nextflix", reul: "를" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-intro", { name: "claudle", reul: "을" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-done", { name: "nextflix", reul: "를" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-done", { name: "claudle", reul: "을" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-vercel-success", { name: "nextflix", ga: "가" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-vercel-success", { name: "claudle", ga: "이" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-github", { name: "nextflix", neun: "는" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-github", { name: "claudle", neun: "은" }],
  ["tutorials/01-nextflix/12-deploy.md", "clone-deploy-prod-run", { n: "6", next: "7" }],
  ["tutorials/02-claudle/12-deploy.md", "clone-deploy-prod-run", { n: "5", next: "6" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-paste", { name: "nextflix", neun: "는" }],
  ["tutorials/02-claudle/README.md", "clone-readme-paste", { name: "claudle", neun: "은" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-first-steps", { name: "nextflix", reul: "를" }],
  ["tutorials/02-claudle/README.md", "clone-readme-first-steps", { name: "claudle", reul: "을" }],
  ["tutorials/01-nextflix/README.md", "clone-readme-image-tip", { pic: "작품 그림" }],
  ["tutorials/02-claudle/README.md", "clone-readme-image-tip", { pic: "그림" }],
  ["tutorials/01-nextflix/11-check.md", "clone-check-qa", { auth: "05-auth-profiles.md" }],
  ["tutorials/02-claudle/11-check.md", "clone-check-qa", { auth: "05-auth-chats.md" }],
  ["tutorials/01-nextflix/06-catalog-db.md", "qa-row-plan", {}],
  ["tutorials/01-nextflix/07-search.md", "qa-row-plan", {}],
  ["tutorials/01-nextflix/08-my-list.md", "qa-row-plan", {}],
  ["tutorials/01-nextflix/09-rating.md", "qa-row-plan", {}],
  ["tutorials/01-nextflix/10-watch.md", "qa-row-plan", {}],
  ["tutorials/02-claudle/06-chat-manage.md", "qa-row-plan", {}],
  ["tutorials/02-claudle/10-artifacts.md", "qa-row-security", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "qa-row-see", {}],
  ["tutorials/samples/01-project.md", "qa-row-run", {}],
  ["tutorials/samples/01-project.md", "qa-row-trust", {}],
  ["tutorials/01-nextflix/04-screens.md", "qa-row-transition", {}],
  ["tutorials/01-nextflix/README.md", "qa-row-transition", {}],
  ["tutorials/samples/05-build.md", "qa-row-transition", {}],
  ["tutorials/02-claudle/04-screens.md", "qa-row-markdown", {}],
  ["tutorials/02-claudle/README.md", "qa-row-markdown", {}],
  ["tutorials/01-nextflix/06-catalog-db.md", "feature-round-review", { n: "5" }],
  ["tutorials/01-nextflix/07-search.md", "feature-round-review", { n: "5" }],
  ["tutorials/01-nextflix/08-my-list.md", "feature-round-review", { n: "6" }],
  ["tutorials/01-nextflix/09-rating.md", "feature-round-review", { n: "5" }],
  ["tutorials/01-nextflix/10-watch.md", "feature-round-review", { n: "7" }],
  ["tutorials/02-claudle/06-chat-manage.md", "feature-round-review", { n: "5" }],
  ["tutorials/02-claudle/07-ai-reply.md", "feature-round-review", { n: "5" }],
  ["tutorials/02-claudle/08-search.md", "feature-round-review", { n: "5" }],
  ["tutorials/02-claudle/09-projects.md", "feature-round-review", { n: "5" }],
  ["tutorials/02-claudle/10-artifacts.md", "feature-round-review", { n: "4" }],
  ["tutorials/01-nextflix/README.md", "clone-cost-row", { stage: "1장 프로젝트 만들기", time: "cost.stage.setup.time", usd: "1", note: "예상" }],
  ["tutorials/01-nextflix/README.md", "clone-cost-row", { stage: "3장 디자인 정하기(구성도로 고르기)", time: "cost.stage.clone.design.time", usd: "4", note: "같음. 시안을 그리면 약 {{v:cost.stage.clone.mockup.time}}, 2달러 더 들고 이미지 요금은 따로예요" }],
  ["tutorials/01-nextflix/README.md", "clone-cost-row", { stage: "11장 검사와 다듬기", time: "cost.stage.clone.check.time", usd: "8", note: "예상" }],
  ["tutorials/01-nextflix/README.md", "clone-cost-row", { stage: "12장 배포", time: "cost.stage.clone.deploy.time", usd: "5", note: "예상. 계정 가입과 로그인 허락 시간은 빼요" }],
  ["tutorials/02-claudle/README.md", "clone-cost-row", { stage: "1장 프로젝트 만들기", time: "cost.stage.setup.time", usd: "1", note: "예상" }],
  ["tutorials/02-claudle/README.md", "clone-cost-row", { stage: "3장 디자인 정하기(구성도로 고르기)", time: "cost.stage.clone.design.time", usd: "4", note: "같음. 시안을 그리면 약 {{v:cost.stage.clone.mockup.time}}, 2달러 더 들고 이미지 요금은 따로예요" }],
  ["tutorials/02-claudle/README.md", "clone-cost-row", { stage: "11장 검사와 다듬기", time: "cost.stage.clone.check.time", usd: "8", note: "예상" }],
  ["tutorials/02-claudle/README.md", "clone-cost-row", { stage: "12장 배포", time: "cost.stage.clone.deploy.time", usd: "5", note: "예상. 계정 가입과 로그인 허락 시간은 빼요" }],
  ...Object.entries(PRESETS).flatMap(([name, p]) => {
    const f = `tutorials/samples/${name}.md`;
    return [
      [f, "preset-pack", { name }],
      [f, "preset-remix", { name, ...p.remix }],
      [f, "preset-scratch-intro", {}],
      [f, "screen-prompt", { folder: name, concept: p.concept }],
      [f, "preset-next-steps", {}],
      [f, "trouble-pack", { name }],
      [f, "preset-scratch-note", {}],
      [f, "limit-line", { name }],
      [f, "cost-note", {}],
      [f, "preset-cost-detail", {}],
      [f, "preset-real-service", p.order ? { tail: " 앞의 것부터 차례로 하면 쉬워요." } : {}],
    ];
  }),
  ...TPL.flatMap((t, i) => TPL_README.map(([b, ...args]) => [`templates/${t}/README.md`, `tpl-readme-${b}`, args[i]])),
];
